### ISSUE TITLE
0x800705aa exceptions

### ISSUE THREAD

**Issue by derossm** [LePresidente/modorganizer#45] opened 2017-01-14 15:57 UTC
ModOrganizer seems to lose all visibility of files possibly after a certain amount of ram is used via a game launched through it (which causes the game to crash since suddenly the virtual file structure is gone in a "simulated drive failure"), and think the system is out of resources. It's hard to get useful information, because it won't produce logs since it gets stuck in 0x800705aa exceptions i.e. unable to write the logs to disk or allocate memory to store them et cetera. Got a terabyte of space on the drive the game, mods, and MO2 is on. Also have at least 8GB of system ram free at peak usage. This is Windows 10, running MO2b4r2.

Everything is back when I relaunch the program, despite getting bombarded with invalid mod index pop-up exceptions while trying to close.

**Comment by LePresidente** [comment] 2017-01-14 17:33
How big is your mods list?
How long till you see the crash?
If it happens again please upload the logs (should be in your profile folder under logs)

**Comment by EsOmEs** [comment] 2017-01-14 17:45
I got  similar symptom. In addition to that, if I close MO2 I get some error messages that it was unable to write to its ini file and update its settings although the path semms fine and the file exists. As I am running MO as admin, it shouldnt be a rights issue but might be related to your error description.

**Comment by Abstremik** [comment] 2017-01-20 19:29
I have also seen this problem. similarly I am also running MO2 as admin and just in case installed Steam outside Program Files directory

**Comment by fireundubh** [comment] 2017-01-21 12:12
I see this error in 2.0.8.2:

![2017-01-21 04_07_48](https://cloud.githubusercontent.com/assets/1261664/22174276/3ed17f28-df8f-11e6-891d-a84dcc843c39.png)

Canceling produces this error:

![2017-01-21 04_09_23](https://cloud.githubusercontent.com/assets/1261664/22174286/6ebb2dba-df8f-11e6-9e48-e72f07ea0cde.png)

### Steps to Reproduce

1. Launch MO.
2. Launch TESV through SKSE, or perhaps any game.
3. #50 occurs, so MO might be in a bad state at this point.
4. Exit game to desktop.
5. Close error dialog from Step 3.
6. Close MO.

**Comment by dragonshardz** [comment] 2017-02-04 07:00
I also just got this issue, but with Fallout 4. Tried to load a different cell and it fell over.

Followed by the following error messages:
![capture 5](https://cloud.githubusercontent.com/assets/1939923/22616591/928d19e4-ea64-11e6-9f43-4f664046760c.png)

**Comment by EsOmEs** [comment] 2017-02-08 17:36
Seems to be happening still with version 2.0.8.3. Got it three times in a row now regardless if I start up the game itself or another tool like FO4Edit, etc. 

I have lots of mods (300+) with zillions of files. Might this be the problem? Does not happen with 2.0.8.0 though.
[usvfs.zip](https://github.com/LePresidente/modorganizer/files/761465/usvfs.zip)
[MO_logs.zip](https://github.com/LePresidente/modorganizer/files/761468/MO_logs.zip)

attaching log files...

Hope that helps.

**Comment by Luarst** [comment] 2017-09-25 22:45
Not the issue, I had way less then that, and still got these errors.. (Somewhere between 10-13, I Recently Installed MO.) I'll try to get logs of it next time it happens as well as I deleted the files for installing on a different SSD.

**Comment by Silarn** [comment] 2017-11-28 00:23
Long-standing memory crashes. Fixed on latest builds.

**Closed by Silarn** 2017-11-28 00:23 UTC
