### ISSUE TITLE
LOOT crashes on close when started from MO

### ISSUE THREAD

**Issue by bartmoss** [LePresidente/modorganizer#22] opened 2016-12-31 22:45 UTC
LOOT 10.2 crashes on close when started via MO. I also observe that startup is slow: The window appears, but remains white for several seconds. These issues do not occur when launching it from NMM.

This is when I launch LOOT via the app selection, where one can also launch Skyrim. LOOT will not launch at all via the "sort" button. Will submit separate issue for that.

The changed load order is not taken over by MO, either.

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	Loot.exe
  Application Version:	0.10.2.0
  Application Timestamp:	5842dd47
  Fault Module Name:	usvfs_x86.dll
  Fault Module Version:	0.2.2.0
  Fault Module Timestamp:	5766aa70
  Exception Code:	c0000005
  Exception Offset:	000cb19e
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	1073
  Additional Information 2:	107361da68c79d1366b92a26d9cef5f3
  Additional Information 3:	f170
  Additional Information 4:	f17054badf47953a1c4c05cabd691128

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

**Comment by LePresidente** [comment] 2017-01-18 09:38
Can't reproduce this? Can you still verify this happens for you using the latest release

**Comment by kevlar127** [comment] 2017-02-10 17:42
This happens for me, with MO v2.0.8.3, and the latest LOOT 10.3, run as an app.  After closing LOOT, LOOT crashes, and all the DLC Plugins are disabled and moved to the end of my load order.  
LOOT 10.0 crashes afterwards as well, but the DLC plugins are not touched.
The 'Sort' button using the LOOT API seems to work.

**Comment by Silarn** [comment] 2017-11-28 00:32
This ticket is pretty old now and I haven't heard of any issues with the latest builds.

**Closed by Silarn** 2017-11-28 00:32 UTC
