### ISSUE TITLE
v2.0.8.3 Fallout 4 Will Not Use Profile-Specific INI Files

### ISSUE THREAD

**Issue by DacioRomero** [LePresidente/modorganizer#91] opened 2017-07-01 10:27 UTC
When using the [Fallout 4 Configuration Tool](http://www.nexusmods.com/fallout4/mods/102) when directed it to use the INI files in a profile's directory, nothing would change in-game (e.g. Always Active turned on would still pause the game when alt-tabbing). When changing anti-aliasing using the configurator in the profile's INI, it was not updated in the game launcher. Anything changed in the launcher would be immediately reset, leading to the conclusion that it was using the read-only INI's in My Documents despite "Local Game Settings" being checked. Hopefully this can be fixed soon because there are most likely people who have different INI settings they use for different playthroughs of the game. Mod Organizer was installed in the game directory and set to portable mode if it matters and is not run as administrator.

**Comment by BerenOneHand** [comment] 2017-07-19 17:36
I can confirm this issue and also confirmed that Mod organizer is not using profile specific INI files. When you save the file in the INI editor, it saves the file in the %localappdata%/ModOrganizer/ directory and not the %BASE_DIR%/profiles directory.

Fallout 4 config is pointing to the "My Games\Fallout4" directory when running it through F4SE, through MO 2 v2.0.8.3.

**Comment by BerenOneHand** [comment] 2017-07-19 17:41
I believe the following error is also related to this issue.
![mo2errorpng](https://user-images.githubusercontent.com/23358562/28381200-3c78b602-6cba-11e7-992e-60f2b3140b2c.PNG)

**Comment by GSDFan** [comment] 2017-07-23 10:34
While I believe that the profile specific ini is broken, you have to make sure that "Local Game Settings" is checked for that profile.
This will disable the ini editor and enable the configurator. That is why you see the error that the configurator has failed message. MO will copy and also rename the ini file when this option is checked or un-checked in the profile.

**Comment by BerenOneHand** [comment] 2017-07-23 22:24
Local game settings is ticked...

![image](https://user-images.githubusercontent.com/23358562/28503404-73eee012-7006-11e7-843c-4d31161eb48c.png)

**Comment by Silarn** [comment] 2017-11-01 16:04
Please try the latest build of 2.1 from the Discord server to see if it resolves your issue. Our testers have reported that this is working.

**Comment by Silarn** [comment] 2017-12-07 20:24
In 2.1, due to various reasons, Local Game Settings were essentially **always** enabled. Recent fixes should have resolved this in the current test builds and turning Local Game Settings on or off should work as expected.

**Closed** 2017-12-07 20:24 UTC
Labels: bug, handle issues
