### ISSUE TITLE
Infinite loading when misclicking "Install With NMM"

### ISSUE THREAD

**Issue by Kayomn** [LePresidente/modorganizer#66] opened 2017-03-06 09:58 UTC
I should specify I have only tested this issue with Webkit-based browsers, such as Chromium and Opera. Ergo I'm not sure if it's present in Gecko or any others.

I stumbled this issue when I misclicked a Skyrim mod mistaking it for a Special Edition item. Upon doing this it seems the browser will forever try to connect to Mod Organizer and wait for a response. Nothing hangs but the cursor enters a state of infinite "doing something".

My two cents would be to send a response from the program just to let the browser know the game isn't configured with Mod Organizer so it can stop trying to contact the application, if that's possible.

**Comment by dieDoktor** [comment] 2017-04-14 14:25
I'm curious, did this issue also create an environment where multiple (for me infinite) instances of the nxm-handler process was started? I need to go about trying to recreate the problem, but just wondering if that's the same experience you had...

**Comment by Kayomn** [comment] 2017-04-15 13:34
The bug is easily repeatable by attempting to "Download with NMM" a game that you haven't set up, such as misclicking a Skyrim link for your Skyrim SE Mod Organizer instance.

As for whether what your first question asked happens I'll check and get back to you.

**Comment by Kayomn** [comment] 2017-04-19 12:12
I can reproduce the bug. All I have to do is invoke the nxm handler via download with NMM for an unregistered game and it will continually try to create new instances of the nmm proxy and delete them from memory when they fail.

**Comment by azraal** [comment] 2017-04-19 16:25
On my side I get this infinite nxm handler even with configured games:
I have my "setup" that way:
fo4 (portable mode) no issue
new vegas -> issues
skyrim (the old one) -> issues

I also have old portable installations for each of those games that I didn't use for years. This I guess could also cause a conflict...
I confirmed that the nxmhandler launched was from the one I'm using right now.

**Comment by Kayomn** [comment] 2017-04-19 16:30
Are you reassigning your manage with nxm whenever you change games. Pretty sure the issue is just caused by trying to download with nmm any game its not assigned to associate with at that moment. Eg if you set it up to associate it with your Fallout 4 instance then try downloading a skyrocket mod it'll get confused because it thinks you want to download a Fallout 4 mod. This is all just speculation at the moment but will follow it up when I get a chance to.

**Comment by azraal** [comment] 2017-04-19 20:17
No, I just clicked on the button to change game... I just tried your workaround and it seems to do the trick.
Thanks. So it's really an association issue.

**Comment by Kayomn** [comment] 2017-04-19 20:21
Yeah. It seems like the nxm handler doesn't know what to do whenever you try to install a mod for the game it's not currently assigned to manage.

It really should auto-assign itself based on whatever instance you're running at that time and handle invalid downloads properly

**Comment by azraal** [comment] 2017-04-19 21:12
Maybe it's possible to assign the protocol to another executable that checks if the game is correctly assigned  and only then pass the data to nxmhandler. Maybe auto reassign it if necessary before launching the download proper.

**Comment by Silarn** [comment] 2017-11-28 00:34
This sounds like it could be an issue with 32-bit games, but I'm not sure if it still exists. I guess I'll need to test an old game some time.

**Comment by Silarn** [comment] 2017-11-28 00:35
I believe this is a duplicate of #62.

**Comment by Silarn** [comment] 2017-12-08 18:19
Closing as duplicate.

**Closed by Silarn** 2017-12-08 18:19 UTC
Labels: duplicate, needinfo
