### ISSUE TITLE
Save Games From Profiles Aren't Being Loaded (SkyrimSE)

### ISSUE THREAD

**Issue by blomstertj** [LePresidente/modorganizer#4] opened 2016-12-21 16:24 UTC
I have two profiles for SkyrimSE with local save games ticked.  When I start the game under a specific profile the saves are not copied into the save directory and the game gives me the option for "New" and not load or continue.
FYI My "Documents" folder is not in the standard location for Windows (C:\Users\username\Documents) mine is on a separate drive but I have remapped the location of the library.

**Comment by ZachHaber** [comment] 2016-12-28 06:17
Here's how the skyrimSE plugin is determining the location of your "Documents" folder:
First it tries this function with FOLDERID_Documents as the argument.
https://msdn.microsoft.com/en-us/library/windows/desktop/bb762188(v=vs.85).aspx
Then if that fails, It searches the registry for "Software\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders" entry "personal" (apparently) I think that should be changed to "Common Documents", but I'm not entirely certain.
Can you check if any of those methods are valid for finding your remapped "Documents" folder?
Also, if you make a save file from loading the game without MO can you check if MO can then find it (they should appear under saves)?

**Comment by blomstertj** [comment] 2017-01-06 22:23
That registry entry: "Software\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders" has a value "Common Documents" and that is %PUBLIC%\Documents which is C:\Users\Public\Documents.  But having that folder open when using a profile with local save games enabled and no global characters nothing is being written to that folder so I don't think MO is using that folder specifically.

**Comment by MaddBomber83** [comment] 2017-01-08 05:48
I also have this issue.  Maybe mod organizer needs an additional path to set.

Normally it shoud find the User\Documents\my games\Skyrim Special Edition\  (windows 10)
I have mine in Onedrive\ blahj blaw bledsh\ so MO does not know what to do.

I even tried making a junction in my user folder to point to the documents folder.  No change.

Me Too!

**Comment by ZachHaber** [comment] 2017-01-19 18:21
Blomstertj, If you have local save games enabled, mod organizer will write the save games to the location you specify, it will then map that folder to the "C:\Users\Public\Documents\my games\Skyrim Special Edition\Saves." It will never write to your documents if local saves are enabled.

For both of you, where do the save game files from skyrimSE land when you run it normally (without MO)?

**Comment by blomstertj** [comment] 2017-01-19 18:27
All of my SkyrimSE saves are located in D:\Libraries\Documents\My Games\Skyrim Special Edition
I remapped the Documents library to that location but if I did not it would just save to C:\Users\tanner\Documents\My Games\Skyrim Special Edition.  I have nothing in my Public Documents folder at all (completely empty directory) and from my experience I have never had a game write to that directory.

My MO is expecting there to be a "C:\Users\Public\Documents\my games\Skyrim Special Edition\Saves" path and since there isn't it just to write them to that directory.  MO probably isn't able to create directories.

**Comment by ZachHaber** [comment] 2017-01-19 20:10
Okay, that explains my confusion. It should be personal rather than common documents, as that is the correct registry entry. The problem is that windows 10 doesn't have the "personal" registry entry under user shell folders. I need to figure out how to get the location of documents folder in win 10.

**Comment by ZachHaber** [comment] 2017-01-19 20:23
What is does %USERPROFILE%\Documents expand out to? Because that should lead to the correct documents folder.

**Comment by blomstertj** [comment] 2017-01-19 23:25
I will check on that information when I get home. Stay tuned

**Comment by blomstertj** [comment] 2017-01-20 01:33
That's really strange.  So when I put %userprofile%\Documents in File Explorer it goes to C:\Users\tanner\Documents but that directory is empty.  When I type in command prompt `echo %userprofile%\Documents` the output is `C:\Users\tanner\Documents`

That registry path shows this the documents path is in there but it's with a random string of letters/numbers.  
![image](https://cloud.githubusercontent.com/assets/19897967/22132176/13e839c6-de7e-11e6-9ba8-4d7fe8f0280b.png)

**Comment by ZachHaber** [comment] 2017-01-21 00:23
Check your mo_interface log, should be at %localappdata%\ModOrganizer\SkryimSE\logs
Tell me what the line that starts with "[D] reading save games from" says. And if that is where your profile is.

Is there a Skyrim Special Edition folder in C:\Users\tanner\Documents\my games? If so, delete it, because that might be the issue.

Do local saves work for any other games?

**Comment by blomstertj** [comment] 2017-01-21 01:00
⁣​I will get that soon, probably tomorrow night I think. There's no folders in C:\Users\tanner\Documents so that shouldn't be an issue. I have not tried local saves for other games but I'll try for Fallout 4 and original Skyrim. I can try for Oblivion to if you want too haha.

**Comment by blomstertj** [comment] 2017-01-22 02:58
AFAIK when you create a Profile with Local Save Games the behavior SHOULD be to copy the saves from that profile to the game directory to be read.  I have not tried profiles before upgrading to MO2 so I just wanted to double check if my logic is correct in assuming that.

I used the following method to make these profiles and set up the settings.
I made my profile for my character with these settings:
![image](https://cloud.githubusercontent.com/assets/19897967/22179472/adf6da7a-e01a-11e6-87ab-a55d701970aa.png)

I clicked Transfer Saves and I used Move to move them into the profile like so:
![image](https://cloud.githubusercontent.com/assets/19897967/22179478/d0e5aeda-e01a-11e6-8a22-98e2067b26e1.png)

I tried Skyrim.  I made a profile and enabled local savegames.  I moved them over to that profile and the game only let me start a new game.  I have attached the logs you might find interesting.  I attached my uvfs log but it is very large.
[SkyrimLogs.zip](https://github.com/LePresidente/modorganizer/files/721646/SkyrimLogs.zip)

I tried Fallout 4. 
I then launched the game with this profile active and I couldn't resume my game.  Again the logs for this game are attached.
[Fallout4Logs.zip](https://github.com/LePresidente/modorganizer/files/721650/Fallout4Logs.zip)

Now I try SkyrimSE
Same issue as the previous games.  Logs are attached.
[SkyrimSELogs.zip](https://github.com/LePresidente/modorganizer/files/721654/SkyrimSELogs.zip)

**Comment by Silarn** [comment] 2017-12-08 23:17
This issue should be fixed on the latest builds. If you try them and it still doesn't work I will reopen the ticket.

**Closed by Silarn** 2017-12-08 23:17 UTC
