### ISSUE TITLE
2.0.8.1 hanging when installing .wav files for Skyrim SE

### ISSUE THREAD

**Issue by tryguy** [LePresidente/modorganizer#28] opened 2017-01-03 08:42 UTC
I accidentally put all these issues in TanninOne's git (without even realizing I was there and not here).

Attempting to install Realistic Water Two, and MO hangs towards the end when it tries to install the sound files.

**Comment by fireundubh** [comment] 2017-01-04 02:07
This might be a dupe of #18.

**Closed** 2017-11-28 00:30 UTC
Labels: duplicate
