### ISSUE TITLE
HiDPI Support

### ISSUE THREAD

**Issue by nassoor** [LePresidente/modorganizer#245] opened 2018-02-27 11:22 UTC
# The problem

MO is very hard to use on High DPI screens.

# Environment

* Mod Organizer Version that exhibits the issue: 2.1.1
* Desktop OS/version used to run Mod Organizer: Windows 10

# Details

To reproduce:
1. If you have a screen with high DPI, set display scaling to anything higher 100%.
2. Launch MO.

# Example:

I uploaded the image in half the resolution that it appears on my screen to hopefully demonstrate the problem.

![untitled](https://user-images.githubusercontent.com/2208840/36725466-71c85328-1bc7-11e8-9482-6fe17550fd69.png)

**Comment by Al12rs** [comment] 2018-02-27 11:42
Duplicate of #223 . I implemented High DPI scaling support in the development build available on the discord sever. Could you test it out and report if that works for you?

**Comment by nassoor** [comment] 2018-02-27 18:56
The build fixes the issue. 👍

I apologize for not searching better before submitting the issue.

**Comment by SuperSandro2000** [comment] 2018-02-27 19:41
Plz close this issue then

**Comment by Al12rs** [comment] 2018-02-28 08:52
Don't worry I got it.

**Closed by Al12rs** 2018-02-28 08:52 UTC
Labels: duplicate, potential fix
