### ISSUE TITLE
2.0.8.3: MO Unchecks all DLC masters when closing LOOT app after sorting

### ISSUE THREAD

**Issue by r3Fuze** [LePresidente/modorganizer#58] opened 2017-02-12 22:05 UTC
Information:
ModOrganizer: 2.0.8.3
LOOT: 0.10.3 also tried with 0.10.1 and 0.10.2
Latest Fallout 4 with all DLC
Fallout 4 installed on C:\
MO and LOOT installed on D:\ but tried on C:\ too
Using portable profile

This also happens on MO 2.0.7 but I figured it would be better to post here.

Only mod installed is Unofficial Fallout 4 Patch but I have tried with other mods as well.
I launch LOOT from inside MO, click sort, no changes need to be made, exit LOOT and then all my DLC masters and moves them to the bottom of the load order.

I also noticed that the load order in MO never matches the order in LOOT.

Let me know if you need more information

**Comment by Lady-Luck** [comment] 2017-02-22 12:45
Happens to me too.

**Comment by r3Fuze** [comment] 2017-02-22 14:16
I just formatted my PC and reinstalled everything but I still have this issue. I really have no idea what is happening.

**Comment by paradoxbound** [comment] 2017-02-26 15:56
Ditto

**Comment by LePresidente** [comment] 2017-05-06 17:39
Duplicate of https://github.com/LePresidente/modorganizer/issues/12

**Closed** 2017-05-06 17:39 UTC
Labels: duplicate
